import Head from 'next/head'
import CapturedPokemonCardContainer from '../components/CapturedPokemonCardContainer'
import { useEffect } from 'react';
import getAllStorage from '../util/getAllStorage';

export default function Captured(props) {

    // wait until localstorage can be accessed
    useEffect(() => {
        props.setCapturedPokemon(getAllStorage())
    }
        , []);

    return <>
        <Head>
            <title>Pokedex</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <CapturedPokemonCardContainer
            capturedPokemon={props.capturedPokemon}
            showPopup={props.showPopup}
            setShowPopup={props.setShowPopup} />
    </>
}