import Head from 'next/head'
import CapturedPokemonCardContainer from '../components/CapturedPokemonCardContainer'
import { useEffect } from 'react';

export default function Captured(props) {

    // returns all pokemon values from localstorage
    function allStorage() {

        if (typeof window !== 'undefined') {
            var values = [],
                keys = Object.keys(localStorage),
                i = keys.length;

            while (i--) {
                ('order' in JSON.parse(localStorage.getItem(keys[i]))) ?
                    values.push(JSON.parse(localStorage.getItem(keys[i]))) : console.log('error');
            }

            return values;
        }
    }

    // wait until localstorage can be accessed
    useEffect(() => {
        props.setCapturedPokemon(allStorage())
    }
        , []);

    return <>
        <Head>
            <title>Pokedex</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <CapturedPokemonCardContainer
            capturedPokemon={props.capturedPokemon}
            showPopup={props.showPopup}
            setShowPopup={props.setShowPopup} />
    </>
}