import { useEffect, useState, useContext } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import PokemonCardContainer from '../components/PokemonCardContainer.js'
import CapturePopup from '../components/CapturePopup';
import CapturedPokemonCardContainer from '../components/CapturedPokemonCardContainer';
import {AppContext} from './AppContext.js'

export default function Home(props) {

  /* const [currentPokemon, setCurrentPokemon] = useState({});
  const [capturedPokemon, setCapturedPokemon] = useState([]);
  const [showDetails, setShowDetails] = useState(false);
  const [showPopup, setShowPopup] = useState(false); */

  /* const context = useContext(AppContext);
  console.log(`context: ${context}`);
  console.log(context);
  console.log(props.temp) */

  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {props.showPopup ? <CapturePopup
      currentPokemon={props.currentPokemon}
      capturedPokemon={props.capturedPokemon}
      setCapturedPokemon={props.setCapturedPokemon}/> : ''}

      <PokemonCardContainer 
      currentPokemon={props.currentPokemon}
      setCurrentPokemon={props.setCurrentPokemon}
      showDetails={props.showDetails}
      setShowDetails={props.setShowDetails}
      showPopup={props.showPopup}
      setShowPopup={props.setShowPopup}
      capturedPokemon={props.capturedPokemon}
      data={props.data}/>

      
      
    </>
  )
}

// this get called on every request
export async function getServerSideProps(context) {
  
  const listEndPoint = 'https://pokeapi.co/api/v2/pokemon?limit=20&offset=0';
  const res = await fetch(listEndPoint);
  const data = await res.json();

  /* const [details] = await Promise.all(data.results.map( async url => {
    const res = await fetch(url);
    return await res.json()}
    )); */

  return {
    props: {
      data,
      /* details */
    },
  }
}
