import { useEffect, useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'
import PokemonCardContainer from '../components/PokemonCardContainer.js'

export default function Home(props) {

  const [currentPokemon, setCurrentPokemon] = useState({});
  const [showDetails, setShowDetails] = useState(false);

  return (
    <Layout>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* {console.log(props.details)} */}
      <PokemonCardContainer 
      currentPokemon={currentPokemon}
      setCurrentPokemon={setCurrentPokemon}
      showDetails={showDetails}
      setShowDetails={setShowDetails}
      data={props.data}/>
      
    </Layout>
  )
}

// this get called on every request
export async function getServerSideProps(context) {
  
  const listEndPoint = 'https://pokeapi.co/api/v2/pokemon?limit=20&offset=0';
  const res = await fetch(listEndPoint);
  const data = await res.json();

  /* const [details] = await Promise.all(data.results.map( async url => {
    const res = await fetch(url);
    return await res.json()}
    )); */

  return {
    props: {
      data,
      /* details */
    },
  }
}
